FROM node:lts-alpine

EXPOSE 3000

ENV DB_URI=mongodb://telzir-backend-admin:supersecretbackendadminpassword@database:27017/?retryWrites=true&w=majority
ENV PORT=3000

WORKDIR /usr/src/app

USER node

ENTRYPOINT [ "npm" , "run", "dev" ]
